[build-system]
requires = ["setuptools >= 74.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sstatics"
version = "0.0.0"
dependencies = [
    "dash~=2.18",
    "dash-bootstrap-components~=1.6",
    "numpy~=2.1",
]
requires-python = ">=3.11"
readme = "README.md"

[project.optional-dependencies]
dev = [
    "flake8>=7.1.1",
    "pylint>=3.1.1",
]

[tool.setuptools.packages.find]
where = ["sstatics"]

[tool.pylint.'MESSAGES CONTROL']
errors-only = "True"